services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=Gogik
      - POSTGRES_PASSWORD=2005206a
      - POSTGRES_DB=bank_app
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://Gogik:2005206a@postgres:5432/bank_app?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]

